environment:
    PYTHON: "C:\\Python34"
    PATH: "C:\\Python34;C:\\Python34\\Scripts;%PATH%"
install:
    - python -m ensurepip
    - pip install tox
build_script:
    - python --version
test_script:
    - tox -e py34
